const { Post } = require('../models');

const postData = [
  {
    title: 'Sample Post 1',
    post_body:
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam volutpat commodo sed egestas. Eget mauris pharetra et ultrices neque ornare aenean euismod. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. At tellus at urna condimentum mattis pellentesque id nibh. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Commodo ullamcorper a lacus vestibulum. Nisi porta lorem mollis aliquam ut porttitor. Dui accumsan sit amet nulla facilisi morbi. Libero justo laoreet sit amet cursus sit. Nunc congue nisi vitae suscipit. Purus in massa tempor nec feugiat. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Diam volutpat commodo sed egestas egestas fringilla phasellus. Pellentesque habitant morbi tristique senectus et netus. Nisl nunc mi ipsum faucibus vitae aliquet nec. Senectus et netus et malesuada. Dolor purus non enim praesent elementum facilisis leo vel fringilla.
      
      Enim nec dui nunc mattis. Adipiscing vitae proin sagittis nisl rhoncus mattis. Aliquet enim tortor at auctor urna nunc id. Non consectetur a erat nam at lectus. Tincidunt arcu non sodales neque. Aliquet nec ullamcorper sit amet risus. Volutpat diam ut venenatis tellus. Non enim praesent elementum facilisis leo vel fringilla. Massa ultricies mi quis hendrerit dolor magna eget. Placerat in egestas erat imperdiet sed euismod nisi. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Odio tempor orci dapibus ultrices in. Sit amet massa vitae tortor condimentum lacinia. Vulputate dignissim suspendisse in est ante in nibh mauris. Sit amet massa vitae tortor. At volutpat diam ut venenatis tellus in metus vulputate.

      Sed velit dignissim sodales ut eu sem integer vitae justo. Duis at tellus at urna condimentum. Amet nulla facilisi morbi tempus iaculis urna id. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Vitae turpis massa sed elementum tempus egestas sed. Nisi quis eleifend quam adipiscing vitae proin. Eget egestas purus viverra accumsan in nisl nisi. Lectus vestibulum mattis ullamcorper velit. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Amet risus nullam eget felis eget nunc lobortis. Amet facilisis magna etiam tempor orci.

      Potenti nullam ac tortor vitae purus faucibus. Morbi leo urna molestie at. Cursus in hac habitasse platea dictumst quisque sagittis. Libero enim sed faucibus turpis in. Suspendisse sed nisi lacus sed viverra tellus. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Vulputate eu scelerisque felis imperdiet proin. Volutpat est velit egestas dui id ornare arcu odio ut. Sit amet risus nullam eget felis eget nunc lobortis. Mattis nunc sed blandit libero volutpat. In mollis nunc sed id semper risus in hendrerit. Vitae tempus quam pellentesque nec nam aliquam sem. Aliquet eget sit amet tellus. Fusce ut placerat orci nulla. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Nibh sed pulvinar proin gravida hendrerit lectus a. At auctor urna nunc id cursus.

      Velit aliquet sagittis id consectetur purus ut. Maecenas pharetra convallis posuere morbi leo urna molestie. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Gravida arcu ac tortor dignissim convallis aenean. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Risus viverra adipiscing at in. Scelerisque felis imperdiet proin fermentum leo vel. Eget aliquet nibh praesent tristique. Nibh venenatis cras sed felis eget velit aliquet. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. At lectus urna duis convallis convallis tellus id interdum velit. Sit amet massa vitae tortor condimentum lacinia quis vel.`
    ,
    user_id: 1
  },
  {
    title: 'Sample Post 2',
    post_body:
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam volutpat commodo sed egestas. Eget mauris pharetra et ultrices neque ornare aenean euismod. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. At tellus at urna condimentum mattis pellentesque id nibh. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Commodo ullamcorper a lacus vestibulum. Nisi porta lorem mollis aliquam ut porttitor. Dui accumsan sit amet nulla facilisi morbi. Libero justo laoreet sit amet cursus sit. Nunc congue nisi vitae suscipit. Purus in massa tempor nec feugiat. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Diam volutpat commodo sed egestas egestas fringilla phasellus. Pellentesque habitant morbi tristique senectus et netus. Nisl nunc mi ipsum faucibus vitae aliquet nec. Senectus et netus et malesuada. Dolor purus non enim praesent elementum facilisis leo vel fringilla.

      Enim nec dui nunc mattis. Adipiscing vitae proin sagittis nisl rhoncus mattis. Aliquet enim tortor at auctor urna nunc id. Non consectetur a erat nam at lectus. Tincidunt arcu non sodales neque. Aliquet nec ullamcorper sit amet risus. Volutpat diam ut venenatis tellus. Non enim praesent elementum facilisis leo vel fringilla. Massa ultricies mi quis hendrerit dolor magna eget. Placerat in egestas erat imperdiet sed euismod nisi. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Odio tempor orci dapibus ultrices in. Sit amet massa vitae tortor condimentum lacinia. Vulputate dignissim suspendisse in est ante in nibh mauris. Sit amet massa vitae tortor. At volutpat diam ut venenatis tellus in metus vulputate.

      Sed velit dignissim sodales ut eu sem integer vitae justo. Duis at tellus at urna condimentum. Amet nulla facilisi morbi tempus iaculis urna id. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Vitae turpis massa sed elementum tempus egestas sed. Nisi quis eleifend quam adipiscing vitae proin. Eget egestas purus viverra accumsan in nisl nisi. Lectus vestibulum mattis ullamcorper velit. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Amet risus nullam eget felis eget nunc lobortis. Amet facilisis magna etiam tempor orci.

      Potenti nullam ac tortor vitae purus faucibus. Morbi leo urna molestie at. Cursus in hac habitasse platea dictumst quisque sagittis. Libero enim sed faucibus turpis in. Suspendisse sed nisi lacus sed viverra tellus. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Vulputate eu scelerisque felis imperdiet proin. Volutpat est velit egestas dui id ornare arcu odio ut. Sit amet risus nullam eget felis eget nunc lobortis. Mattis nunc sed blandit libero volutpat. In mollis nunc sed id semper risus in hendrerit. Vitae tempus quam pellentesque nec nam aliquam sem. Aliquet eget sit amet tellus. Fusce ut placerat orci nulla. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Nibh sed pulvinar proin gravida hendrerit lectus a. At auctor urna nunc id cursus.

      Velit aliquet sagittis id consectetur purus ut. Maecenas pharetra convallis posuere morbi leo urna molestie. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Gravida arcu ac tortor dignissim convallis aenean. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Risus viverra adipiscing at in. Scelerisque felis imperdiet proin fermentum leo vel. Eget aliquet nibh praesent tristique. Nibh venenatis cras sed felis eget velit aliquet. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. At lectus urna duis convallis convallis tellus id interdum velit. Sit amet massa vitae tortor condimentum lacinia quis vel.`
    ,
    user_id: 1
  },
  {
    title: 'Sample Post 3',
    post_body:
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam volutpat commodo sed egestas. Eget mauris pharetra et ultrices neque ornare aenean euismod. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. At tellus at urna condimentum mattis pellentesque id nibh. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Commodo ullamcorper a lacus vestibulum. Nisi porta lorem mollis aliquam ut porttitor. Dui accumsan sit amet nulla facilisi morbi. Libero justo laoreet sit amet cursus sit. Nunc congue nisi vitae suscipit. Purus in massa tempor nec feugiat. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Diam volutpat commodo sed egestas egestas fringilla phasellus. Pellentesque habitant morbi tristique senectus et netus. Nisl nunc mi ipsum faucibus vitae aliquet nec. Senectus et netus et malesuada. Dolor purus non enim praesent elementum facilisis leo vel fringilla.

      Enim nec dui nunc mattis. Adipiscing vitae proin sagittis nisl rhoncus mattis. Aliquet enim tortor at auctor urna nunc id. Non consectetur a erat nam at lectus. Tincidunt arcu non sodales neque. Aliquet nec ullamcorper sit amet risus. Volutpat diam ut venenatis tellus. Non enim praesent elementum facilisis leo vel fringilla. Massa ultricies mi quis hendrerit dolor magna eget. Placerat in egestas erat imperdiet sed euismod nisi. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Odio tempor orci dapibus ultrices in. Sit amet massa vitae tortor condimentum lacinia. Vulputate dignissim suspendisse in est ante in nibh mauris. Sit amet massa vitae tortor. At volutpat diam ut venenatis tellus in metus vulputate.

      Sed velit dignissim sodales ut eu sem integer vitae justo. Duis at tellus at urna condimentum. Amet nulla facilisi morbi tempus iaculis urna id. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Vitae turpis massa sed elementum tempus egestas sed. Nisi quis eleifend quam adipiscing vitae proin. Eget egestas purus viverra accumsan in nisl nisi. Lectus vestibulum mattis ullamcorper velit. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Amet risus nullam eget felis eget nunc lobortis. Amet facilisis magna etiam tempor orci.

      Potenti nullam ac tortor vitae purus faucibus. Morbi leo urna molestie at. Cursus in hac habitasse platea dictumst quisque sagittis. Libero enim sed faucibus turpis in. Suspendisse sed nisi lacus sed viverra tellus. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Vulputate eu scelerisque felis imperdiet proin. Volutpat est velit egestas dui id ornare arcu odio ut. Sit amet risus nullam eget felis eget nunc lobortis. Mattis nunc sed blandit libero volutpat. In mollis nunc sed id semper risus in hendrerit. Vitae tempus quam pellentesque nec nam aliquam sem. Aliquet eget sit amet tellus. Fusce ut placerat orci nulla. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Nibh sed pulvinar proin gravida hendrerit lectus a. At auctor urna nunc id cursus.

      Velit aliquet sagittis id consectetur purus ut. Maecenas pharetra convallis posuere morbi leo urna molestie. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Gravida arcu ac tortor dignissim convallis aenean. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Risus viverra adipiscing at in. Scelerisque felis imperdiet proin fermentum leo vel. Eget aliquet nibh praesent tristique. Nibh venenatis cras sed felis eget velit aliquet. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. At lectus urna duis convallis convallis tellus id interdum velit. Sit amet massa vitae tortor condimentum lacinia quis vel.`
    ,
    user_id: 2
  },
  {
    title: 'Sample Post 4',
    post_body:
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam volutpat commodo sed egestas. Eget mauris pharetra et ultrices neque ornare aenean euismod. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. At tellus at urna condimentum mattis pellentesque id nibh. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Commodo ullamcorper a lacus vestibulum. Nisi porta lorem mollis aliquam ut porttitor. Dui accumsan sit amet nulla facilisi morbi. Libero justo laoreet sit amet cursus sit. Nunc congue nisi vitae suscipit. Purus in massa tempor nec feugiat. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Diam volutpat commodo sed egestas egestas fringilla phasellus. Pellentesque habitant morbi tristique senectus et netus. Nisl nunc mi ipsum faucibus vitae aliquet nec. Senectus et netus et malesuada. Dolor purus non enim praesent elementum facilisis leo vel fringilla.

      Enim nec dui nunc mattis. Adipiscing vitae proin sagittis nisl rhoncus mattis. Aliquet enim tortor at auctor urna nunc id. Non consectetur a erat nam at lectus. Tincidunt arcu non sodales neque. Aliquet nec ullamcorper sit amet risus. Volutpat diam ut venenatis tellus. Non enim praesent elementum facilisis leo vel fringilla. Massa ultricies mi quis hendrerit dolor magna eget. Placerat in egestas erat imperdiet sed euismod nisi. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Odio tempor orci dapibus ultrices in. Sit amet massa vitae tortor condimentum lacinia. Vulputate dignissim suspendisse in est ante in nibh mauris. Sit amet massa vitae tortor. At volutpat diam ut venenatis tellus in metus vulputate.

      Sed velit dignissim sodales ut eu sem integer vitae justo. Duis at tellus at urna condimentum. Amet nulla facilisi morbi tempus iaculis urna id. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Vitae turpis massa sed elementum tempus egestas sed. Nisi quis eleifend quam adipiscing vitae proin. Eget egestas purus viverra accumsan in nisl nisi. Lectus vestibulum mattis ullamcorper velit. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Amet risus nullam eget felis eget nunc lobortis. Amet facilisis magna etiam tempor orci.

      Potenti nullam ac tortor vitae purus faucibus. Morbi leo urna molestie at. Cursus in hac habitasse platea dictumst quisque sagittis. Libero enim sed faucibus turpis in. Suspendisse sed nisi lacus sed viverra tellus. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Vulputate eu scelerisque felis imperdiet proin. Volutpat est velit egestas dui id ornare arcu odio ut. Sit amet risus nullam eget felis eget nunc lobortis. Mattis nunc sed blandit libero volutpat. In mollis nunc sed id semper risus in hendrerit. Vitae tempus quam pellentesque nec nam aliquam sem. Aliquet eget sit amet tellus. Fusce ut placerat orci nulla. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Nibh sed pulvinar proin gravida hendrerit lectus a. At auctor urna nunc id cursus.

      Velit aliquet sagittis id consectetur purus ut. Maecenas pharetra convallis posuere morbi leo urna molestie. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Gravida arcu ac tortor dignissim convallis aenean. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Risus viverra adipiscing at in. Scelerisque felis imperdiet proin fermentum leo vel. Eget aliquet nibh praesent tristique. Nibh venenatis cras sed felis eget velit aliquet. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. At lectus urna duis convallis convallis tellus id interdum velit. Sit amet massa vitae tortor condimentum lacinia quis vel.`
    ,
    user_id: 2
  }
];

const seedPosts = () => Post.bulkCreate(postData);

module.exports = seedPosts;
